services:
  db:
    image: postgres:16
    container_name: habitflow-pgsql-container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: habitflow_db
      POSTGRES_USER: habitflow_user
      POSTGRES_PASSWORD: habitflow_password

  backend:
    image: habitflow-backend:latest
    build:
      context: ./
    container_name: habitflow-backend-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/habitflow_db
      SPRING_DATASOURCE_USERNAME: habitflow_user
      SPRING_DATASOURCE_PASSWORD: habitflow_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db:
    driver: local